---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure jj config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/jj"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Copy main jj configuration"
  ansible.builtin.copy:
    src: config.toml
    dest: "{{ ansible_user_dir }}/.config/jj/config.toml"
    mode: '0644'

- name: "{{ role_name }} | Copy conf.d directory"
  ansible.builtin.copy:
    src: conf.d
    dest: "{{ ansible_user_dir }}/.config/jj/conf.d"
    mode: "0644"
    directory_mode: "0755"
    force: true

